### ISSUE TITLE
[Bug] : Add button or panel to layout function puts it into custom panel if selected first.

### ISSUE THREAD

**Issue by chunky-panda** [MintyTrebor/BtnCmd#18] opened 2024-06-16 04:55 UTC
The "add button" or "add panel" function puts the new objects in the wrong place.

On a new install, I first clicked "create and edit panels" ... experimented with some stuff there. I saved and exited.

Then I clicked on "create and edit layouts" ... then clicked on "add button" and "add panels" but no new objects were added to the layout. When I go back to the new panel I created, I see the buttons and panels I added when I was in the layout edit mode.

When I go back to the "create and edit layouts", it is only after I create a new tab that the "add button" and "add panels" puts it into the layout.

**Expected behaviour**

While in "create and edit layout" mode, I expected the new buttons and panels to be added to the layout, but instead were added to the previously created panel.

**Version Info:**
 - OS: SBC Latest, 3.5.2
 - Browser Edge Latest Version 126.0.2592.56 (Official build) (arm64)
 - BtnCmd Version 1.03.03
 - DWC Version 3.5.2

Thank you for this great plug-in. I just installed it and it looks very promising for my project.

**Comment by MintyTrebor** [comment] 2024-06-16 07:18
Confirmed - looks like a bug has crept in to the tab indexing function - i'll look into it.
As you state - once you create a new Tab in layout mode everything behaves properly - even adding items to the first default tab.

**Comment by MintyTrebor** [comment] 2024-06-16 13:29
Fixed in 01.03.04

**Closed as completed by MintyTrebor** 2024-06-16 13:29 UTC
Labels: bug
